In [1]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.base import BaseEstimator,TransformerMixin
import re
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor

In [3]:
dataset = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")
dataset

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [9]:
X = dataset[[x for x in dataset.columns if x != "Sleep Disorder"]]
y = dataset["Sleep Disorder"]

In [25]:
X.loc[:, [0, 1]] = X.apply(lambda x: [float(x) for x in re.findall(r"(\d{2,3})\/(\d{2,3})", x["Blood Pressure"])[0]], 
        axis=1, result_type="expand")

In [21]:
X = X.rename(columns={0: "SYS", 1: "DIA"})

In [22]:
int_col = [x for x in X.select_dtypes(int)]
X[int_col] = X[int_col].applymap(lambda x: float(x))

In [23]:
X.head(3)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,SYS,DIA
0,1.0,Male,27.0,Software Engineer,6.1,6.0,42.0,6.0,Overweight,126/83,77.0,4200.0,126.0,83.0
1,2.0,Male,28.0,Doctor,6.2,6.0,60.0,8.0,Normal,125/80,75.0,10000.0,125.0,80.0
2,3.0,Male,28.0,Doctor,6.2,6.0,60.0,8.0,Normal,125/80,75.0,10000.0,125.0,80.0

In [27]:
 data_pipeline = ColumnTransformer([
                ("convert_to_catogorical", OrdinalEncoder(),["Gender", "Occupation", "BMI Category"])
], remainder="passthrough")

In [28]:
X_col = X.columns
X = data_pipeline.fit_transform(X)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.